server:
  port: 8091
spring:
  application:
    name: "ms001-authentication"
  devtools:
    add-properties: false
  webflux:
    base-path: "/api"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapters:
  r2dbc:
    host: localhost
    port: 3306
    database: ms001_authentication_db
    username: root
    password: root
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
